language: objective-c
env:
 global:
   - "MODULE_NAME=ti.coremotion"
   - "MODULE_VERSION=1.0.1"
before_install:
    - MODULE_ROOT=$PWD
install:
    - curl -o hyperloop.sh https://raw.githubusercontent.com/appcelerator-modules/ci/master/travis/hyperloop.sh
    - source hyperloop.sh
    - curl -o install.sh https://raw.githubusercontent.com/appcelerator-modules/ci/master/travis/install.sh
    - source install.sh -s 3.3.0.GA
script: 
    - curl -o script.sh https://raw.githubusercontent.com/appcelerator-modules/ci/master/travis/script-hyperloop.sh
    - source script.sh
    - mkdir $MODULE_ROOT/s3
    - NOW=$(date +"%Y%m%d%H%M")
    - echo "cp $MODULE_ROOT/ios/build/$MODULE_NAME-iphone-$MODULE_VERSION.zip $MODULE_ROOT/s3/$MODULE_NAME-iphone-$MODULE_VERSION-$TRAVIS_BRANCH-$NOW.zip"
    - cp $MODULE_ROOT/ios/build/$MODULE_NAME-iphone-$MODULE_VERSION.zip $MODULE_ROOT/s3/$MODULE_NAME-iphone-$MODULE_VERSION-$TRAVIS_BRANCH-$NOW.zip
deploy:
  provider: s3
  access_key_id: AKIAJEU4ONO4EVCH6DRA
  secret_access_key:
    secure: DjoNYXNIjuURlV+tIXBJtaL6sZGI46OgT2IkYfk/iETBTz6QUUQnPcvkMjcl63TjVPKlcxwDswAy/iu7+vSg/VTZLk22PTGksPLJf/fV0BNnqlDWpBh8SIcdxoly0Kmwmf41KLG9lI/8IEi1zOL/x/qbA1nKN72RgiXmLISgFjM=
  upload-dir: modules/ti.coremotion
  bucket: builds.appcelerator.com
  local-dir: $TRAVIS_BUILD_DIR/s3/
  skip_cleanup: true
  on:
    repo: appcelerator-modules/ti.coremotion
    branch: master
